platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

target 'EchartsDemo' do

pod 'AFNetworking'
pod 'PureLayout'
pod 'FLEX'
pod 'NYXImagesKit'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'uicontrol-blocks'
pod 'INTULocationManager'
pod 'YYKit'
pod 'MLeaksFinder'
pod 'Masonry'

pod 'iOS-Echarts'

pod 'Charts'
pod 'ChartsRealm'


end

